### ISSUE TITLE
Captcha is not rendered again after validation in combination with onedrop/ajaxform

### ISSUE THREAD

**Issue by simonschaufi** [die-wegmeister/Wegmeister.Recaptcha#17]
### Description

After submitting the form via ajax and not clicking the captcha, the validation message is shown to click the captcha but the captcha itself is not shown any more. 

### Steps to Reproduce

1. Install `onedrop/ajaxform:^3.4`
2. Don't click the captcha and submit the form
3. Error message is shown but captcha is not rendered

#### Expected behavior

Captcha is rerendered

#### Actual behavior

Captcha is not rendered again after validation error.

**Comment by Benjamin-K** [comment]
Hi @simonschaufi,

thanks for your feedback. My time is currently very limited and due to the new cookie policy we do currently have no site that includes this package any more. You can try using the new Captcha field `Wegmeister.Recaptcha:CaptchaV3` and see if that helps. Otherwise maybe google has some information on this. Feel free to fork this package and create a pull request. I can update the package if there is a PR but do not have the time currently to test things and update it. Sorry for that. Maybe this will change in one or two month.

Regards,
Benjamin

**Comment by simonschaufi** [comment]
Ok, thank you for the feedback. I will see what works best for me.

**Comment by Benjamin-K** [comment]
Hey @simonschaufi,
can you give us an update on the current state here?

**Comment by simonschaufi** [comment]
I didn't have the time yet to work on a workaround and it's still broken as seen here: https://www.simonschaufelberger.de/de/kontakt.html Just submit the form with errors and then the captcha is not rendered again.

**Comment by Benjamin-K** [comment]
Ok, i think this is not primarily a problem of this package but a problem of recaptcha not running the init function again after an asynchronous request. A way to solve this, is to manually call `grecaptcha.render` when your response comes back from the server and still shows the form. For more information on it, have a look at [reCAPTCHA v2 Guide / Examples](https://developers.google.com/recaptcha/docs/display#js_api) and skip `onloadCallback` but check for the existence of `grecaptcha`.

**Comment by Benjamin-K** [comment]
@simonschaufi Do you need any further information on this? Otherwise i would like to close this issue as this package was not designed to work with async forms. I hope my last message helped you pointing you into the right direction.

**Comment by simonschaufi** [comment]
I didn't have the time yet to work on my own website and this issue but I think this would solve the issue.
